# (name, facility_type, city, state, tier, has_cold_storage, latitude, longitude)

facilities_data = [
    # Teaching Hospitals
    (
        "Lagos University Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Idi-Araba",
        "Lagos",
        "MAJOR",
        True,
        6.5172,
        3.3549,
    ),
    (
        "Lagos State University Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Ikeja",
        "Lagos",
        "MAJOR",
        True,
        6.6018,
        3.3515,
    ),
    # General Hospitals
    (
        "Gbagada General Hospital",
        "GENERAL_HOSPITAL",
        "Gbagada",
        "Lagos",
        "MAJOR",
        True,
        6.5528,
        3.3869,
    ),
    (
        "Ikorodu General Hospital",
        "GENERAL_HOSPITAL",
        "Ikorodu",
        "Lagos",
        "SECONDARY",
        True,
        6.6194,
        3.5105,
    ),
    # Community Pharmacies
    (
        "MedPlus Pharmacy Victoria Island",
        "COMMUNITY_PHARMACY",
        "Victoria Island",
        "Lagos",
        "MAJOR",
        True,
        6.4281,
        3.4219,
    ),
    (
        "HealthPlus Pharmacy Ikeja",
        "COMMUNITY_PHARMACY",
        "Ikeja",
        "Lagos",
        "MAJOR",
        True,
        6.5954,
        3.3420,
    ),
    (
        "MedPlus Pharmacy Surulere",
        "COMMUNITY_PHARMACY",
        "Surulere",
        "Lagos",
        "MAJOR",
        True,
        6.5051,
        3.3518,
    ),
    (
        "Alpha Pharmacy Yaba",
        "COMMUNITY_PHARMACY",
        "Yaba",
        "Lagos",
        "MAJOR",
        True,
        6.5110,
        3.3709,
    ),
    (
        "Mushin PHC",
        "PRIMARY_HEALTH_CENTER",
        "Mushin",
        "Lagos",
        "SECONDARY",
        False,
        6.5333,
        3.3500,
    ),
    (
        "Agege PHC",
        "PRIMARY_HEALTH_CENTER",
        "Agege",
        "Lagos",
        "SECONDARY",
        False,
        6.6167,
        3.3167,
    ),
    (
        "Aminu Kano Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Kano",
        "Kano",
        "MAJOR",
        True,
        12.0022,
        8.5167,
    ),
    (
        "Murtala Muhammad Specialist Hospital",
        "GENERAL_HOSPITAL",
        "Kano",
        "Kano",
        "MAJOR",
        True,
        11.9964,
        8.5250,
    ),
    (
        "Muhammad Abdullahi Wase Hospital",
        "GENERAL_HOSPITAL",
        "Kano",
        "Kano",
        "MAJOR",
        True,
        12.0500,
        8.5333,
    ),
    (
        "Bello Pharmacy Kano",
        "COMMUNITY_PHARMACY",
        "Kano",
        "Kano",
        "MAJOR",
        True,
        11.9917,
        8.5167,
    ),
    (
        "University of Port Harcourt Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Port Harcourt",
        "Rivers",
        "MAJOR",
        True,
        4.8997,
        6.9244,
    ),
    (
        "Braithwaite Memorial Specialist Hospital",
        "GENERAL_HOSPITAL",
        "Port Harcourt",
        "Rivers",
        "MAJOR",
        True,
        4.7731,
        7.0103,
    ),
    (
        "Rivers State University Teaching Hospital",
        "GENERAL_HOSPITAL",
        "Port Harcourt",
        "Rivers",
        "MAJOR",
        True,
        4.8014,
        6.9839,
    ),
    (
        "MedMark Pharmacy PH",
        "COMMUNITY_PHARMACY",
        "Port Harcourt",
        "Rivers",
        "MAJOR",
        True,
        4.8156,
        7.0498,
    ),
    (
        "PharmaCare Rumuola",
        "COMMUNITY_PHARMACY",
        "Port Harcourt",
        "Rivers",
        "MAJOR",
        False,
        4.8322,
        6.9917,
    ),
    (
        "Diobu PHC",
        "PRIMARY_HEALTH_CENTER",
        "Port Harcourt",
        "Rivers",
        "SECONDARY",
        False,
        4.7833,
        7.0167,
    ),
    (
        "Eleme PHC",
        "PRIMARY_HEALTH_CENTER",
        "Eleme",
        "Rivers",
        "TERTIARY",
        False,
        4.7833,
        7.1167,
    ),
    (
        "University of Abuja Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Gwagwalada",
        "FCT",
        "MAJOR",
        True,
        8.9433,
        7.0803,
    ),
    (
        "Wuse General Hospital",
        "GENERAL_HOSPITAL",
        "Wuse",
        "FCT",
        "MAJOR",
        True,
        9.0833,
        7.4833,
    ),
    (
        "Asokoro District Hospital",
        "GENERAL_HOSPITAL",
        "Asokoro",
        "FCT",
        "MAJOR",
        True,
        9.0333,
        7.5333,
    ),
    (
        "Garki Pharmacy",
        "COMMUNITY_PHARMACY",
        "Garki",
        "FCT",
        "MAJOR",
        True,
        9.0500,
        7.4833,
    ),
    (
        "RxPharmacy Gwarimpa",
        "COMMUNITY_PHARMACY",
        "Gwarimpa",
        "FCT",
        "MAJOR",
        True,
        9.1167,
        7.3833,
    ),
    (
        "Nyanya PHC",
        "PRIMARY_HEALTH_CENTER",
        "Nyanya",
        "FCT",
        "SECONDARY",
        False,
        8.9833,
        7.5500,
    ),
    (
        "Kubwa PHC",
        "PRIMARY_HEALTH_CENTER",
        "Kubwa",
        "FCT",
        "SECONDARY",
        False,
        9.1500,
        7.3167,
    ),
    (
        "University College Hospital Ibadan",
        "TEACHING_HOSPITAL",
        "Ibadan",
        "Oyo",
        "MAJOR",
        True,
        7.4000,
        3.9167,
    ),
    (
        "Adeoyo Maternity Teaching Hospital",
        "GENERAL_HOSPITAL",
        "Ibadan",
        "Oyo",
        "MAJOR",
        True,
        7.3833,
        3.8833,
    ),
    (
        "Ring Road State Hospital",
        "GENERAL_HOSPITAL",
        "Ibadan",
        "Oyo",
        "MAJOR",
        True,
        7.3667,
        3.8667,
    ),
    (
        "Jericho Pharmacy",
        "COMMUNITY_PHARMACY",
        "Ibadan",
        "Oyo",
        "MAJOR",
        True,
        7.3833,
        3.8667,
    ),
    (
        "Bodija Pharmacy",
        "COMMUNITY_PHARMACY",
        "Ibadan",
        "Oyo",
        "MAJOR",
        False,
        7.4333,
        3.9167,
    ),
    (
        "Agbowo PHC",
        "PRIMARY_HEALTH_CENTER",
        "Ibadan",
        "Oyo",
        "SECONDARY",
        False,
        7.4417,
        3.9000,
    ),
    (
        "Ogbomoso PHC",
        "PRIMARY_HEALTH_CENTER",
        "Ogbomoso",
        "Oyo",
        "TERTIARY",
        False,
        8.1333,
        4.2500,
    ),
    (
        "Ahmadu Bello University Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Zaria",
        "Kaduna",
        "MAJOR",
        True,
        11.1760,
        7.6047,
    ),
    (
        "Barau Dikko Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Kaduna",
        "Kaduna",
        "MAJOR",
        True,
        10.5167,
        7.4333,
    ),
    (
        "Yusuf Dantsoho Memorial Hospital",
        "GENERAL_HOSPITAL",
        "Kaduna",
        "Kaduna",
        "MAJOR",
        True,
        10.5000,
        7.4167,
    ),
    (
        "Kaduna Central Pharmacy",
        "COMMUNITY_PHARMACY",
        "Kaduna",
        "Kaduna",
        "MAJOR",
        True,
        10.5167,
        7.4333,
    ),
    (
        "Zaria PHC",
        "PRIMARY_HEALTH_CENTER",
        "Zaria",
        "Kaduna",
        "SECONDARY",
        False,
        11.0833,
        7.7167,
    ),
    (
        "Kafanchan PHC",
        "PRIMARY_HEALTH_CENTER",
        "Kafanchan",
        "Kaduna",
        "TERTIARY",
        False,
        9.5833,
        8.3000,
    ),
    (
        "Federal Medical Centre Asaba",
        "TEACHING_HOSPITAL",
        "Asaba",
        "Delta",
        "MAJOR",
        True,
        6.2000,
        6.7333,
    ),
    (
        "Central Hospital Warri",
        "GENERAL_HOSPITAL",
        "Warri",
        "Delta",
        "MAJOR",
        True,
        5.5167,
        5.7500,
    ),
    (
        "Delta State University Teaching Hospital",
        "GENERAL_HOSPITAL",
        "Oghara",
        "Delta",
        "SECONDARY",
        True,
        5.9667,
        5.9000,
    ),
    (
        "Asaba Mall Pharmacy",
        "COMMUNITY_PHARMACY",
        "Asaba",
        "Delta",
        "MAJOR",
        True,
        6.1833,
        6.7500,
    ),
    (
        "Ughelli PHC",
        "PRIMARY_HEALTH_CENTER",
        "Ughelli",
        "Delta",
        "SECONDARY",
        False,
        5.5000,
        6.0000,
    ),
    (
        "University of Benin Teaching Hospital",
        "TEACHING_HOSPITAL",
        "Benin City",
        "Edo",
        "MAJOR",
        True,
        6.3333,
        5.6333,
    ),
    (
        "Central Hospital Benin",
        "GENERAL_HOSPITAL",
        "Benin City",
        "Edo",
        "MAJOR",
        True,
        6.3333,
        5.6167,
    ),
    (
        "Stella Obasanjo Hospital",
        "GENERAL_HOSPITAL",
        "Benin City",
        "Edo",
        "MAJOR",
        True,
        6.3500,
        5.6000,
    ),
    (
        "Ring Road Pharmacy Benin",
        "COMMUNITY_PHARMACY",
        "Benin City",
        "Edo",
        "MAJOR",
        True,
        6.3333,
        5.6167,
    ),
]
