# (generic_name, therapeutic_class, stocking_level, requires_cold_chain, base_demand, form, category, strength)
medications_data = [
    (
        "Artemether-Lumefantrine",
        "Antimalarial",
        1,
        False,
        200,
        "pack",
        "CRITICAL",
        "20mg/120mg",
    ),
    (
        "Artesunate-Amodiaquine",
        "Antimalarial",
        1,
        False,
        150,
        "pack",
        "CRITICAL",
        "50mg/135mg",
    ),
    (
        "Artesunate Injection",
        "Antimalarial",
        3,
        False,
        50,
        "vial",
        "CRITICAL",
        "60mg/2ml",
    ),
    (
        "Sulfadoxine-Pyrimethamine",
        "Antimalarial",
        1,
        False,
        100,
        "tablet",
        "ESSENTIAL",
        "500mg/25mg",
    ),
    ("Amoxicillin", "Antibiotic", 1, False, 300, "capsule", "ESSENTIAL", "500mg"),
    (
        "Amoxicillin-Clavulanate",
        "Antibiotic",
        2,
        False,
        100,
        "tablet",
        "ESSENTIAL",
        "625mg",
    ),
    ("Metronidazole", "Antibiotic", 1, False, 200, "tablet", "STANDARD", "400mg"),
    ("Ciprofloxacin", "Antibiotic", 2, False, 80, "tablet", "ESSENTIAL", "500mg"),
    ("Ceftriaxone", "Antibiotic", 3, False, 60, "vial", "CRITICAL", "1g"),
    ("Azithromycin", "Antibiotic", 2, False, 100, "tablet", "ESSENTIAL", "500mg"),
    ("Paracetamol", "Analgesic", 1, False, 500, "tablet", "ESSENTIAL", "500mg"),
    ("Ibuprofen", "Analgesic", 1, False, 200, "tablet", "ESSENTIAL", "400mg"),
    ("Diclofenac", "Analgesic", 2, False, 100, "tablet", "STANDARD", "50mg"),
    ("Amlodipine", "Antihypertensive", 2, False, 150, "tablet", "ESSENTIAL", "5mg"),
    ("Lisinopril", "Antihypertensive", 2, False, 120, "tablet", "ESSENTIAL", "10mg"),
    (
        "Hydrochlorothiazide",
        "Antihypertensive",
        2,
        False,
        100,
        "tablet",
        "STANDARD",
        "25mg",
    ),
    ("Metformin", "Antidiabetic", 2, False, 200, "tablet", "ESSENTIAL", "500mg"),
    ("Glibenclamide", "Antidiabetic", 2, False, 80, "tablet", "STANDARD", "5mg"),
    (
        "Insulin Human Regular",
        "Antidiabetic",
        2,
        True,
        50,
        "vial",
        "CRITICAL",
        "100IU/ml",
    ),
    (
        "Oral Rehydration Salts",
        "Gatrointenstinal",
        1,
        False,
        300,
        "sachet",
        "ESSENTIAL",
        "1L sachet",
    ),
    ("Zinc Sulfate", "Gatrointenstinal", 1, False, 250, "tablet", "STANDARD", "20mg"),
    ("Omeprazole", "Gatrointenstinal", 2, False, 100, "capsule", "ESSENTIAL", "20mg"),
    (
        "Salbutamol Inhaler",
        "Respiratory",
        1,
        False,
        80,
        "inhaler",
        "ESSENTIAL",
        "100mcg/puff",
    ),
    ("Prednisolone", "Respiratory", 2, False, 60, "tablet", "STANDARD", "5mg"),
    ("Chlorpheniramine", "Antihistamine", 1, False, 150, "tablet", "STANDARD", "4mg"),
    (
        "Ferrous Sulfate + Folic Acid",
        "Vitamin_supplement",
        1,
        False,
        300,
        "tablet",
        "ESSENTIAL",
        "65mg/400mcg",
    ),
    (
        "Vitamin B Complex",
        "Vitamin_supplement",
        1,
        False,
        200,
        "tablet",
        "STANDARD",
        "B1/B2/B6/B12",
    ),
    (
        "Levonorgestrel-Ethinylestradiol",
        "Contraceptive",
        2,
        False,
        100,
        "pack",
        "ESSENTIAL",
        "0.15mg/0.03mg",
    ),
    (
        "Tenofovir-Lamivudine-Efavirenz",
        "Antiretroviral",
        3,
        False,
        40,
        "tablet",
        "CRITICAL",
        "300/300/600mg",
    ),
    ("Oxytocin", "Uterotonics", 3, True, 30, "ampoule", "CRITICAL", "10IU/ml"),
]

stocking_rule = {
    "PRIMARY_HEALTH_CENTER": [1],
    "COMMUNITY_PHARMACY": [1, 2],
    "GENERAL_HOSPITAL": [1, 2, 3],
    "TEACHING_HOSPITAL": [1, 2, 3, 4],
}
